# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_interconnect_0_0/design_2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_interconnect_0_0 || ORIG_REF_NAME==design_2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_myPrescaler_0_0/design_2_myPrescaler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_myPrescaler_0_0 || ORIG_REF_NAME==design_2_myPrescaler_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_0_0/design_2_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_fifo_mm_s_1_0/design_2_axi_fifo_mm_s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==design_2_axi_fifo_mm_s_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_myI2STx_v1_0_0_0/design_2_myI2STx_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_myI2STx_v1_0_0_0 || ORIG_REF_NAME==design_2_myI2STx_v1_0_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mySPIRxTx_v1_0_0_0/design_2_mySPIRxTx_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_mySPIRxTx_v1_0_0_0 || ORIG_REF_NAME==design_2_mySPIRxTx_v1_0_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_myPrescaler_1_0/design_2_myPrescaler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_myPrescaler_1_0 || ORIG_REF_NAME==design_2_myPrescaler_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
