# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/finalproject_3/finalproject_3.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
# IP: The module: 'design_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/finalproject_3/finalproject_3.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Xilinx/finalproject_3/finalproject_3.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
# IP: The module: 'design_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/finalproject_3/finalproject_3.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
