# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
# IP: The module: 'design_1_smartconnect_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/bd_892d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_0/bd_892d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_2/bd_892d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_3/bd_892d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_4/bd_892d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_12/bd_892d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
# IP: The module: 'design_1_smartconnect_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/bd_892d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_0/bd_892d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_2/bd_892d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_3/bd_892d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_4/bd_892d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_12/bd_892d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0_ooc.xdc

# XDC: d:/Xilinx/week9_2/week9_2.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
